[tool.poetry]
name = "snake-game"
version = "0.1.0"
description = "A simple Snake game with fruits and bombs"
authors = ["User"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.8"
pygame = "^2.6.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
